name: SSL-Check

on:
  push:
    branches:
      - main
  schedule:
    # 每天 01 点 01 分自动运行
    - cron: "1 11 * * *"

jobs:
  CheckSSL:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install & Build
        run: |
          export TZ='Asia/Shanghai'
          npm i
          npm run build
          cd check-ssl
          chmod +x checker.sh
          ./checker.sh draw.seeyue.top img.seeyue.top matomo.seeyue.top nav.seeyue.top pan.seeyue.top pic.seeyue.top state.seeyue.top uptime.seeyue.top umami.seeyue.top ward.seeyue.top
          cp -rf ./output/ct.json ../public/ct.json
          cd ..
          cp -rf ./src/index.html ./public/index.html
          echo "ssl.seeyue.top" > ./public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
